// SlovíčKO - databáza slovnej zásoby (anglicky -> slovensky)
// Zoradené voľne podľa frekvencie/tém, appka ich pri výbere dňa zamiešava náhodne.
// Skontrolované na duplicitné slovenské preklady, aby sa v jednom dni nikdy neobjavili
// dve rôzne anglické slová s rovnakým slovenským textom.
const WORD_BANK = [
["be","byť"],["have","mať"],["do","robiť"],["say","povedať"],["go","ísť"],
["get","dostať"],["make","urobiť"],["know","vedieť"],["think","myslieť"],["see","vidieť"],
["come","prísť"],["want","chcieť"],["look","pozerať"],["use","používať"],["find","nájsť"],
["give","dať"],["tell","povedať (niekomu)"],["work","pracovať"],["call","zavolať"],["try","skúsiť"],
["ask","opýtať sa"],["need","potrebovať"],["feel","cítiť"],["become","stať sa"],["leave","odísť"],
["put","položiť"],["mean","myslieť (tým)"],["keep","udržať"],["let","dovoliť"],["begin","začínať"],
["seem","zdať sa"],["help","pomôcť"],["talk","rozprávať"],["turn","otočiť"],["start","začať"],
["show","ukázať"],["hear","počuť"],["play","hrať"],["run","bežať"],["move","hýbať sa"],
["like","páčiť sa"],["live","žiť"],["believe","veriť"],["bring","priniesť"],["happen","prihodiť sa"],
["write","písať"],["provide","poskytnúť"],["sit","sedieť"],["stand","stáť"],["lose","stratiť"],
["pay","platiť"],["meet","stretnúť"],["include","zahŕňať"],["continue","pokračovať"],["set","nastaviť"],
["learn","učiť sa"],["change","zmeniť"],["lead","viesť"],["understand","rozumieť"],["watch","sledovať"],
["follow","nasledovať"],["stop","zastaviť"],["create","vytvoriť"],["speak","hovoriť"],["read","čítať"],
["allow","povoliť"],["add","pridať"],["spend","stráviť (čas)"],["grow","rásť"],["open","otvoriť"],
["walk","kráčať"],["win","vyhrať"],["offer","ponúknuť"],["remember","spomenúť si"],["love","milovať"],
["consider","zvážiť"],["appear","objaviť sa"],["buy","kúpiť"],["wait","čakať"],["serve","slúžiť"],
["die","zomrieť"],["send","poslať"],["expect","očakávať"],["build","stavať"],["stay","zostať"],
["fall","padnúť"],["cut","strihať"],["reach","dosiahnuť"],["kill","zabiť"],["remain","pretrvávať"],
["sleep","spať"],["eat","jesť"],["drink","piť"],["drive","viesť (auto)"],["fly","letieť"],
["sing","spievať"],["dance","tancovať"],["laugh","smiať sa"],["cry","plakať"],["smile","usmiať sa"],
["forget","zabudnúť"],["choose","vybrať"],["explain","vysvetliť"],["teach","učiť"],["catch","chytiť"],
["throw","hodiť"],["push","tlačiť"],["pull","ťahať"],["carry","niesť"],["hold","držať"],
["break","zlomiť"],["fix","opraviť"],["clean","čistiť"],["wash","umyť"],["cook","variť"],
["fight","bojovať"],["hope","dúfať"],["wish","priať si"],["visit","navštíviť"],["travel","cestovať"],
["arrive","prísť/pricestovať"],["depart","odísť/odcestovať"],["return","vrátiť sa"],["enjoy","užívať si"],["prefer","uprednostniť"],
["decide","rozhodnúť sa"],["agree","súhlasiť"],["disagree","nesúhlasiť"],["accept","prijať"],["refuse","odmietnuť"],
["suggest","navrhnúť"],["promise","sľúbiť"],["warn","varovať"],["complain","sťažovať sa"],["apologize","ospravedlniť sa"],
["thank","poďakovať"],["celebrate","oslavovať"],["invite","pozvať"],["family","rodina"],["mother","matka"],
["father","otec"],["parent","rodič"],["child","dieťa"],["son","syn"],["daughter","dcéra"],
["brother","brat"],["sister","sestra"],["husband","manžel"],["wife","manželka"],["friend","priateľ"],
["grandmother","stará mama"],["grandfather","starý otec"],["baby","bábätko"],["man","muž"],["woman","žena"],
["boy","chlapec"],["girl","dievča"],["people","ľudia"],["neighbor","sused"],["colleague","kolega"],
["stranger","cudzinec"],["adult","dospelý"],["teenager","tínedžer"],["couple","pár (dvojica)"],["twin","dvojča"],
["cousin","bratranec/sesternica"],["uncle","strýko"],["aunt","teta"],["time","čas"],["day","deň"],
["week","týždeň"],["month","mesiac"],["year","rok"],["hour","hodina"],["minute","minúta"],
["second","sekunda"],["morning","ráno"],["afternoon","popoludnie"],["evening","večer"],["night","noc"],
["today","dnes"],["tomorrow","zajtra"],["yesterday","včera"],["now","teraz"],["later","neskôr"],
["early","skoro"],["late","neskoro"],["soon","čoskoro"],["always","vždy"],["never","nikdy"],
["often","často"],["sometimes","niekedy"],["usually","zvyčajne"],["already","už"],["still","stále"],
["yet","ešte"],["again","znova"],["once","raz/kedysi"],["weekend","víkend"],["holiday","sviatok/dovolenka"],
["season","ročné obdobie"],["century","storočie"],["moment","okamih"],["house","dom"],["home","domov"],
["city","mesto"],["town","mestečko"],["village","dedina"],["country","krajina"],["street","ulica"],
["road","cesta"],["school","škola"],["office","kancelária"],["hospital","nemocnica"],["shop","obchod"],
["market","trh"],["restaurant","reštaurácia"],["hotel","hotel"],["airport","letisko"],["station","stanica"],
["park","park"],["beach","pláž"],["mountain","hora"],["river","rieka"],["lake","jazero"],
["sea","more"],["forest","les"],["field","pole"],["garden","záhrada"],["kitchen","kuchyňa"],
["bedroom","spálňa"],["bathroom","kúpeľňa"],["room","izba"],["door","dvere"],["window","okno"],
["wall","stena"],["floor","podlaha"],["roof","strecha"],["stairs","schody"],["church","kostol"],
["library","knižnica"],["museum","múzeum"],["bridge","most"],["building","budova"],["factory","továreň"],
["farm","farma"],["island","ostrov"],["desert","púšť"],["food","jedlo"],["water","voda"],
["bread","chlieb"],["meat","mäso"],["fish","ryba"],["milk","mlieko"],["cheese","syr"],
["egg","vajce"],["butter","maslo"],["sugar","cukor"],["salt","soľ"],["rice","ryža"],
["pasta","cestoviny"],["soup","polievka"],["salad","šalát"],["fruit","ovocie"],["vegetable","zelenina"],
["apple","jablko"],["banana","banán"],["orange","pomaranč"],["potato","zemiak"],["tomato","paradajka"],
["onion","cibuľa"],["coffee","káva"],["tea","čaj"],["juice","džús"],["wine","víno"],
["beer","pivo"],["breakfast","raňajky"],["lunch","obed"],["dinner","večera"],["cake","torta/koláč"],
["chocolate","čokoláda"],["snack","desiata/maškrta"],["meal","jedlo (chod)"],["body","telo"],["head","hlava"],
["face","tvár"],["eye","oko"],["ear","ucho"],["nose","nos"],["mouth","ústa"],
["hand","ruka"],["arm","paža"],["leg","noha"],["foot","chodidlo"],["finger","prst"],
["hair","vlasy"],["heart","srdce"],["stomach","žalúdok"],["skin","koža"],["bone","kosť"],
["blood","krv"],["health","zdravie"],["illness","choroba"],["pain","bolesť"],["doctor","lekár"],
["nurse","zdravotná sestra"],["medicine","liek"],["tired","unavený"],["sick","chorý"],["healthy","zdravý"],
["strong","silný"],["weak","slabý"],["clothes","oblečenie"],["shirt","košeľa"],["trousers","nohavice"],
["dress","šaty"],["skirt","sukňa"],["shoes","topánky"],["socks","ponožky"],["jacket","bunda"],
["coat","kabát"],["hat","klobúk"],["glasses","okuliare"],["belt","opasok"],["scarf","šál"],
["gloves","rukavice"],["bag","taška"],["weather","počasie"],["sun","slnko"],["moon","mesiac (na oblohe)"],
["star","hviezda"],["sky","obloha"],["rain","dážď"],["snow","sneh"],["wind","vietor"],
["cloud","mrak"],["storm","búrka"],["ice","ľad"],["fire","oheň"],["earth","zem"],
["tree","strom"],["flower","kvetina"],["grass","tráva"],["leaf","list"],["animal","zviera"],
["dog","pes"],["cat","mačka"],["bird","vták"],["horse","kôň"],["cow","krava"],
["sheep","ovca"],["pig","prasa"],["mouse","myš"],["rabbit","zajac/králik"],["bear","medveď"],
["lion","lev"],["snake","had"],["insect","hmyz"],["butterfly","motýľ"],["bee","včela"],
["spider","pavúk"],["color","farba"],["red","červená"],["blue","modrá"],["green","zelená"],
["yellow","žltá"],["black","čierna"],["white","biela"],["purple","fialová"],["pink","ružová"],
["brown","hnedá"],["gray","sivá"],["number","číslo"],["one","jeden"],["two","dva"],
["three","tri"],["ten","desať"],["hundred","sto"],["thousand","tisíc"],["half","polovica"],
["few","málo"],["many","veľa"],["much","veľa (nepočítateľné)"],["little","málo (nepočítateľné)"],["all","všetko"],
["some","nejaké"],["none","žiadne"],["first","prvý"],["last","posledný"],["next","ďalší"],
["same","rovnaký"],["different","odlišný"],["good","dobrý"],["bad","zlý"],["big","veľký"],
["small","malý"],["new","nový"],["old","starý"],["young","mladý"],["long","dlhý"],
["short","krátky"],["high","vysoký"],["low","nízky"],["easy","ľahký"],["difficult","ťažký"],
["important","dôležitý"],["true","pravdivý"],["false","nepravdivý"],["happy","šťastný"],["sad","smutný"],
["angry","nahnevaný"],["afraid","vystrašený"],["surprised","prekvapený"],["beautiful","krásny"],["ugly","škaredý"],
["dirty","špinavý"],["hot","horúci"],["cold","studený"],["warm","teplý"],["cool","chladný"],
["fast","rýchly"],["slow","pomalý"],["loud","hlasný"],["quiet","tichý"],["full","plný"],
["empty","prázdny"],["heavy","ťažký (váha)"],["light","ľahký (váha)"],["expensive","drahý"],["cheap","lacný"],
["free","voľný/zadarmo"],["busy","zaneprázdnený"],["ready","pripravený"],["safe","bezpečný"],["dangerous","nebezpečný"],
["possible","možný"],["impossible","nemožný"],["necessary","nevyhnutný"],["interesting","zaujímavý"],["boring","nudný"],
["funny","zábavný"],["serious","vážny"],["kind","láskavý"],["rude","nezdvorilý"],["polite","zdvorilý"],
["honest","úprimný"],["brave","odvážny"],["proud","hrdý"],["lonely","osamelý"],["nervous","nervózny"],
["calm","pokojný"],["strange","zvláštny"],["normal","normálny"],["public","verejný"],["private","súkromný"],
["local","miestny"],["global","globálny"],["modern","moderný"],["ancient","starobylý"],["comfortable","pohodlný"],
["convenient","výhodný"],["job","zamestnanie"],["career","kariéra"],["business","podnikanie"],["company","firma"],
["boss","šéf"],["employee","zamestnanec"],["manager","manažér"],["meeting","stretnutie"],["project","projekt"],
["task","úloha"],["deadline","termín"],["salary","plat"],["interview","pohovor"],["skill","zručnosť"],
["experience","skúsenosť"],["education","vzdelanie"],["student","študent"],["teacher","učiteľ"],["class","trieda/hodina"],
["lesson","lekcia"],["homework","domáca úloha"],["exam","skúška"],["grade","známka"],["university","univerzita"],
["degree","titul"],["book","kniha"],["page","stránka"],["pen","pero"],["paper","papier"],
["computer","počítač"],["phone","telefón"],["internet","internet"],["email","email"],["screen","obrazovka"],
["car","auto"],["bus","autobus"],["train","vlak"],["plane","lietadlo"],["bicycle","bicykel"],
["ship","loď"],["taxi","taxík"],["ticket","lístok"],["journey","cesta (výprava)"],["trip","výlet"],
["luggage","batožina"],["passenger","cestujúci"],["driver","vodič"],["traffic","doprava (premávka)"],["map","mapa"],
["money","peniaze"],["price","cena"],["cost","náklad"],["cash","hotovosť"],["card","karta"],
["bank","banka"],["store","predajňa"],["customer","zákazník"],["sale","výpredaj"],["discount","zľava"],
["receipt","účtenka"],["bill","účet"],["debt","dlh"],["save","šetriť"],["earn","zarobiť"],
["rich","bohatý"],["poor","chudobný"],["value","hodnota"],["idea","nápad"],["opinion","názor"],
["problem","problém"],["solution","riešenie"],["question","otázka"],["answer","odpoveď"],["reason","dôvod"],
["decision","rozhodnutie"],["choice","voľba"],["mistake","chyba"],["truth","pravda"],["lie","klamstvo"],
["fear","strach"],["dream","sen"],["memory","spomienka"],["feeling","pocit"],["mind","myseľ"],
["thought","myšlienka"],["attention","pozornosť"],["life","život"],["world","svet"],["person","osoba"],
["thing","vec"],["place","miesto"],["case","prípad"],["fact","fakt"],["part","časť"],
["group","skupina"],["way","spôsob"],["word","slovo"],["name","meno"],["story","príbeh"],
["news","správy"],["information","informácia"],["language","jazyk"],["culture","kultúra"],["history","história"],
["society","spoločnosť"],["government","vláda"],["law","zákon"],["war","vojna"],["peace","mier"],
["freedom","sloboda"],["power","moc/sila"],["energy","energia"],["sound","zvuk"],["voice","hlas"],
["music","hudba"],["art","umenie"],["movie","film"],["game","hra"],["sport","šport"],
["team","tím"],["ball","lopta"],["match","zápas"],["prize","cena (výhra)"],["gift","darček"],
["party","večierok"],["wedding","svadba"],["birthday","narodeniny"],["guest","hosť"],["event","udalosť"],
["attack","útočiť"],["attend","zúčastniť sa"],["avoid","vyhnúť sa"],["borrow","požičať si"],["burn","horieť"],
["calculate","vypočítať"],["cancel","zrušiť"],["care","starať sa"],["check","skontrolovať"],["climb","liezť/šplhať"],
["close","zavrieť"],["collect","zbierať"],["compare","porovnať"],["complete","dokončiť"],["confirm","potvrdiť"],
["connect","spojiť"],["contain","obsahovať"],["control","ovládať"],["count","počítať"],["cover","zakryť"],
["cross","prejsť/prekročiť"],["cure","liečiť"],["damage","poškodiť"],["deliver","doručiť"],["deny","poprieť"],
["describe","opísať"],["design","vytvoriť návrh"],["destroy","zničiť"],["develop","rozvíjať"],["disappear","zmiznúť"],
["discover","objaviť"],["discuss","diskutovať"],["divide","rozdeliť"],["doubt","pochybovať"],["download","stiahnuť (súbor)"],
["drop","upustiť"],["educate","vzdelávať"],["encourage","povzbudiť"],["enter","vstúpiť"],["escape","utiecť"],
["examine","preskúmať"],["exchange","vymeniť"],["exist","existovať"],["expand","rozšíriť"],["explore","preskúmať/objavovať"],
["export","vyviezť"],["express","vyjadriť"],["fail","zlyhať"],["fill","naplniť"],["finish","ukončiť"],
["float","plávať (na hladine)"],["fold","zložiť"],["force","donútiť"],["forgive","odpustiť"],["freeze","zamrznúť"],
["gain","získať"],["greet","pozdraviť"],["guess","hádať"],["guide","viesť/sprevádzať"],["handle","zvládnuť"],
["hang","zavesiť"],["hate","nenávidieť"],["heal","hojiť sa"],["hide","skryť"],["hire","najať"],
["hit","udrieť"],["hurt","ubližovať"],["identify","identifikovať"],["ignore","ignorovať"],["imagine","predstaviť si"],
["improve","zlepšiť"],["increase","zvýšiť"],["influence","ovplyvniť"],["inform","informovať"],["insist","trvať na"],
["inspect","prehliadnuť"],["install","nainštalovať"],["introduce","predstaviť"],["invent","vynájsť"],["investigate","vyšetrovať"],
["join","pripojiť sa"],["judge","posúdiť"],["jump","skočiť"],["knock","zaklopať"],["land","pristáť"],
["launch","spustiť"],["lean","opierať sa"],["lend","požičať (niekomu)"],["lift","zdvihnúť"],["limit","obmedziť"],
["link","prepojiť"],["listen","počúvať"],["load","naložiť"],["lock","zamknúť"],["manage","zvládnuť/riadiť"],
["march","pochodovať"],["mark","označiť"],["marry","oženiť sa/vydať sa"],["measure","merať"],["melt","topiť sa"],
["mention","spomenúť"],["mix","miešať"],["multiply","násobiť"],["notice","všimnúť si"],["obey","poslúchať"],
["observe","pozorovať"],["obtain","nadobudnúť"],["occur","vyskytnúť sa"],["order","objednať"],["organize","organizovať"],
["own","vlastniť"],["pack","zbaliť"],["paint","maľovať"],["participate","podieľať sa"],["pass","podať/prejsť"],
["perform","predviesť"],["persuade","presvedčiť"],["plan","plánovať"],["plant","zasadiť"],["point","ukázať prstom"],
["pour","naliať"],["practice","precvičovať"],["predict","predpovedať"],["prepare","pripraviť"],["present","predstaviť (prezentovať)"],
["press","stlačiť"],["pretend","predstierať"],["prevent","zabrániť"],["print","vytlačiť"],["produce","vyrobiť"],
["progress","napredovať"],["promote","povýšiť/propagovať"],["protect","chrániť"],["prove","dokázať"],["publish","publikovať"],
["punish","potrestať"],["purchase","zakúpiť"],["quit","prestať/skončiť"],["raise","zdvihnúť/vychovávať"],["realize","uvedomiť si"],
["recall","vybaviť si"],["receive","obdržať"],["recognize","rozpoznať"],["recommend","odporučiť"],["record","zaznamenať"],
["recover","zotaviť sa"],["reduce","znížiť"],["refer","odkazovať"],["reflect","odzrkadľovať"],["regret","ľutovať"],
["relax","oddychovať"],["release","uvoľniť/vydať"],["rely","spoliehať sa"],["remove","odstrániť"],["repair","opraviť (vec/stroj)"],
["repeat","opakovať"],["replace","nahradiť"],["reply","odpovedať"],["report","hlásiť"],["represent","reprezentovať"],
["request","požiadať"],["require","vyžadovať"],["rescue","zachrániť"],["research","skúmať"],["resist","odolávať"],
["respect","rešpektovať"],["respond","reagovať"],["rest","odpočívať"],["result","vyplynúť"],["reveal","odhaliť"],
["review","posúdiť/recenzovať"],["reward","odmeniť"],["ride","jazdiť (na niečom)"],["ring","zvoniť"],["rise","stúpať"],
["risk","riskovať"],["roll","kotúľať sa"],["rub","trieť"],["ruin","spustošiť"],["satisfy","uspokojiť"],
["scare","vystrašiť"],["schedule","naplánovať"],["scream","kričať"],["search","hľadať"],["seek","hľadať/usilovať sa"],
["select","zvoliť"],["shake","triasť"],["share","zdieľať"],["shine","žiariť"],["shoot","strieľať"],
["shout","vykrikovať"],["shut","zatvoriť"],["signal","signalizovať"],["sign","podpísať"],["skip","preskočiť"],
["slide","kĺzať sa"],["smell","voňať/cítiť"],["smoke","fajčiť"],["solve","vyriešiť"],["sort","triediť"],
["spell","hláskovať"],["spill","rozliať"],["split","rozštiepiť"],["spread","šíriť"],["squeeze","stisnúť"],
["stare","civieť"],["state","uviesť/vyhlásiť"],["steal","ukradnúť"],["stick","prilepiť"],["stir","premiešať"],
["strengthen","posilniť"],["stretch","naťahovať sa"],["struggle","zápasiť/bojovať"],["study","študovať"],["submit","predložiť"],
["succeed","uspieť"],["suffer","trpieť"],["suit","vyhovovať"],["support","podporovať"],["suppose","predpokladať"],
["surprise","prekvapiť"],["surround","obklopiť"],["survive","prežiť"],["suspect","podozrievať"],["swim","plávať"],
["switch","prepnúť"],["take","vziať"],["taste","chutiť/ochutnať"],["tear","trhať"],["tend","mať sklon"],
["test","testovať"],["threaten","hroziť"],["tie","zaviazať"],["touch","dotknúť sa"],["trade","obchodovať"],
["transfer","preniesť/previesť"],["translate","preložiť"],["transport","prepravovať"],["treat","zaobchádzať/liečiť"],["trust","dôverovať"],
["type","písať na klávesnici"],["unite","zjednotiť"],["upload","nahrať (na internet)"],["vote","hlasovať"],["wake","zobudiť sa"],
["waste","plytvať"],["wave","mávať"],["wear","nosiť (oblečenie)"],["weigh","vážiť"],["wonder","premýšľať/čudovať sa"],
["wrap","zabaliť"],["yell","vrešťať"],["able","schopný"],["absent","neprítomný"],["accurate","presný (bez chýb)"],
["active","aktívny"],["actual","skutočný"],["additional","dodatočný"],["adequate","primeraný"],["alone","sám/osamote"],
["alive","živý/nažive"],["annoying","otravný"],["anxious","úzkostlivý"],["automatic","automatický"],["available","dostupný"],
["aware","vedomý si"],["awful","otrasný"],["basic","základný"],["bitter","horký"],["blind","slepý"],
["bold","odvážny/tučný (písmo)"],["bored","znudený"],["bright","jasný"],["broad","obšírny"],["broken","zlomený/pokazený"],
["careful","opatrný"],["careless","nedbalý"],["certain","istý"],["cheerful","veselý"],["clear","jasný/zrozumiteľný"],
["clever","šikovný"],["common","bežný"],["complex","zložitý"],["confident","sebavedomý"],["confused","zmätený"],
["conscious","pri vedomí"],["constant","stály"],["content","spokojný"],["correct","správny"],["crazy","šialený"],
["creative","kreatívny"],["curious","zvedavý"],["current","súčasný"],["curved","zakrivený"],["cute","roztomilý"],
["deaf","hluchý"],["decent","slušný"],["deep","hlboký"],["definite","jednoznačný"],["delicious","lahodný"],
["dense","hustý"],["desperate","zúfalý"],["direct","priamy"],["disabled","zdravotne postihnutý"],["distant","vzdialený"],
["dry","suchý"],["due","splatný/očakávaný"],["dull","nudný/tupý"],["eager","dychtivý"],["earnest","úprimný/vážny"],
["efficient","efektívny"],["elderly","starší (o osobe)"],["embarrassed","zahanbený"],["enormous","obrovský"],["envious","závistlivý"],
["equal","rovný/rovnaký"],["even","rovný/párny"],["eventual","konečný"],["evident","zjavný"],["exact","presne zhodný"],
["excellent","vynikajúci"],["excited","nadšený"],["exhausted","vyčerpaný"],["exotic","exotický"],["extra","navyše"],
["extreme","extrémny"],["fair","spravodlivý"],["faithful","verný"],["familiar","známy"],["famous","slávny"],
["fancy","luxusný/ozdobný"],["far","ďaleký"],["fat","tučný"],["fine","dobrý/v poriadku"],["firm","pevný"],
["fit","fit/vhodný"],["flat","plochý"],["fond","obľubujúci"],["foolish","hlúpy"],["foreign","cudzí/zahraničný"],
["formal","formálny"],["fortunate","šťastný (mať šťastie)"],["fragile","krehký"],["fresh","čerstvý"],["friendly","priateľský"],
["frightened","naľakaný"],["frozen","zamrznutý"],["generous","veľkorysý"],["gentle","jemný"],["genuine","pravý/opravdivý"],
["giant","gigantický"],["glad","rád"],["gorgeous","nádherný"],["grateful","vďačný"],["greedy","chamtivý"],
["guilty","vinný"],["handsome","pekný (o mužovi)"],["hard","tvrdý/ťažký"],["harmful","škodlivý"],["helpful","nápomocný"],
["hidden","skrytý"],["hollow","dutý"],["horrible","strašný"],["huge","ohromný"],["humble","skromný"],
["hungry","hladný"],["identical","identický"],["ill","nevoľný"],["immediate","okamžitý"],["independent","nezávislý"],
["indoor","vnútorný"],["infinite","nekonečný"],["innocent","nevinný"],["intelligent","inteligentný"],["intense","intenzívny"],
["invisible","neviditeľný"],["jealous","žiarlivý"],["joint","spoločný"],["joyful","radostný"],["just","spravodlivý/práve"],
["keen","dychtivý/nadšený"],["large","rozsiahly"],["lazy","lenivý"],["legal","legálny"],["level","rovný/na úrovni"],
["likely","pravdepodobný"],["limited","obmedzený"],["lively","živý/rušný"],["logical","logický"],["loose","voľný"],
["lost","stratený"],["loyal","lojálny"],["lucky","šťastný (šťastena)"],["mad","nahnevaný/šialený"],["magic","kúzelný"],
["major","hlavný/väčší"],["male","mužský"],["married","ženatý/vydatá"],["mature","zrelý"],["messy","neporiadny"],
["mild","mierny"],["minor","menší"],["mixed","zmiešaný"],["moist","vlhký"],["mysterious","tajomný"],
["naked","nahý"],["narrow","úzky"],["native","rodný/domorodý"],["natural","prírodný"],["naughty","neposlušný"],
["nearby","blízky (poloha)"],["neat","upravený"],["negative","negatívny"],["noisy","hlučný"],["obvious","očividný"],
["odd","zvláštny/nepárny"],["official","oficiálny"],["outdoor","vonkajší"],["overall","celkový"],["painful","bolestivý"],
["pale","bledý"],["particular","konkrétny"],["patient","trpezlivý"],["perfect","dokonalý"],["permanent","trvalý"],
["personal","osobný"],["physical","fyzický"],["plain","obyčajný"],["pleasant","príjemný"],["pointless","zbytočný"],
["popular","populárny"],["positive","pozitívny"],["practical","praktický"],["precious","vzácny"],["precise","presný"],
["pregnant","tehotná"],["pretty","pekný/roztomilý"],["previous","predchádzajúci"],["primary","primárny"],["prompt","pohotový"],
["proper","správny/vhodný"],["punctual","dochvíľny"],["pure","čistý"],["quick","hbitý"],["rapid","prudký"],
["rare","zriedkavý"],["raw","surový"],["realistic","realistický"],["recent","nedávny"],["reliable","spoľahlivý"],
["remote","odľahlý"],["responsible","zodpovedný"],["rigid","rigidný/tuhý"],["ripe","zrelý (ovocie)"],["rough","drsný"],
["round","okrúhly"],["salty","slaný"],["scared","vydesený"],["secret","tajný"],["secure","zabezpečený"],
["selfish","sebecký"],["senior","starší/vyšší (pozíciou)"],["sensible","rozumný"],["sensitive","citlivý"],["separate","oddelený"],
["severe","závažný"],["shallow","plytký"],["sharp","ostrý"],["shiny","lesklý"],["shocked","šokovaný"],
["shy","hanblivý"],["significant","významný"],["silent","bezhlučný"],["silly","bláznivý"],["similar","podobný"],
["simple","jednoduchý"],["single","jediný/slobodný"],["skilled","zručný"],["skinny","chudý"],["sleepy","ospalý"],
["slight","nepatrný"],["slippery","šmykľavý"],["smooth","hladký"],["soft","mäkký"],["solid","pevný/tuhý"],
["sore","boľavý"],["sour","kyslý"],["spare","náhradný/voľný"],["special","špeciálny"],["specific","konkrétny/špecifický"],
["spicy","korenistý"],["spoiled","rozmaznaný/pokazený"],["sporty","športový"],["square","štvorcový"],["stable","stabilný"],
["steady","stabilný/rovnomerný"],["steep","strmý"],["sticky","lepkavý"],["stiff","stuhnutý"],["straight","rovný"],
["strict","prísny"],["stubborn","tvrdohlavý"],["stupid","sprostý"],["successful","úspešný"],["sudden","náhly"],
["sufficient","dostatočný"],["suitable","vhodný"],["sunny","slnečný"],["super","super/výborný"],["superior","nadradený"],
["supreme","najvyšší"],["sure","presvedčený"],["sweet","sladký"],["talented","talentovaný"],["tall","vysoký (o postave)"],
["tame","ochočený"],["tasty","chutný"],["temporary","dočasný"],["tender","nežný/jemný"],["tense","napätý"],
["terrible","hrozný"],["thick","hrubý (o predmete)"],["thin","tenký/chudý"],["thirsty","smädný"],["thoughtful","ohľaduplný"],
["tidy","upratany/uprataný"],["tight","tesný"],["tiny","maličký"],["tough","tvrdý/húževnatý"],["typical","typický"],
["unfair","nespravodlivý"],["unique","jedinečný"],["unusual","nezvyčajný"],["upset","rozrušený"],["urgent","naliehavý"],
["used","použitý/zvyknutý"],["useful","užitočný"],["useless","nanič"],["usual","zvyčajný"],["vague","vágny/nejasný"],
["valid","platný"],["various","rôzny"],["vast","obrovský/rozsiahly"],["visible","viditeľný"],["vital","zásadný/životne dôležitý"],
["wealthy","majetný"],["weird","čudný"],["wet","mokrý"],["wide","široký"],["wild","divoký"],
["willing","ochotný"],["wise","múdry"],["worried","znepokojený"],["worth","hodný/hodnota"],["wrong","nesprávny"],
["adventure","dobrodružstvo"],["ambition","ambícia"],["amount","množstvo"],["ancestor","predok"],["angle","uhol"],
["anniversary","výročie"],["announcement","oznámenie"],["apartment","byt"],["appearance","vzhľad"],["appointment","stretnutie/termín"],
["area","oblasť"],["argument","hádka/argument"],["arrival","príchod"],["aspect","aspekt"],["atmosphere","atmosféra"],
["attempt","pokus"],["attitude","postoj"],["audience","publikum"],["author","autor"],["award","ocenenie"],
["background","pozadie"],["balance","rovnováha"],["barrier","prekážka"],["basis","základ"],["battery","batéria"],
["behavior","správanie"],["belief","viera/presvedčenie"],["benefit","výhoda"],["birth","narodenie"],["border","hranica"],
["brain","mozog"],["branch","vetva/pobočka"],["breath","dych"],["budget","rozpočet"],["campaign","kampaň"],
["capacity","kapacita"],["capital","hlavné mesto/kapitál"],["category","kategória"],["cause","príčina"],["ceiling","strop"],
["ceremony","obrad"],["challenge","výzva"],["chance","šanca"],["channel","kanál"],["chapter","kapitola"],
["character","charakter/postava"],["charge","poplatok/náboj"],["charity","charita"],["chart","graf"],["circle","kruh"],
["circumstance","okolnosť"],["citizen","občan"],["climate","podnebie"],["clue","stopa/indícia"],["collection","zbierka"],
["comment","komentár"],["community","komunita"],["competition","súťaž"],["complaint","sťažnosť"],["concept","koncept"],
["conclusion","záver"],["condition","stav/podmienka"],["confidence","sebadôvera"],["conflict","konflikt"],["connection","spojenie"],
["consequence","dôsledok"],["container","nádoba"],["context","kontext"],["contract","zmluva"],["contrast","kontrast"],
["conversation","rozhovor"],["core","jadro"],["corner","roh"],["council","rada (orgán)"],["courage","odvaha"],
["course","kurz/priebeh"],["court","súd"],["creature","tvor"],["crime","zločin"],["crisis","kríza"],
["crowd","dav"],["curriculum","učebný plán"],["custom","zvyk"],["danger","nebezpečenstvo"],["data","údaje"],
["deal","dohoda"],["death","smrť"],["debate","debata"],["decade","desaťročie"],["defense","obrana"],
["delay","meškanie"],["demand","dopyt/požiadavka"],["departure","odchod"],["depth","hĺbka"],["desire","túžba"],
["destination","cieľ (cesty)"],["detail","detail"],["device","zariadenie"],["diet","strava/diéta"],["difference","rozdiel"],
["dimension","rozmer"],["direction","smer"],["disaster","katastrofa"],["discovery","objav"],["disease","ochorenie"],
["distance","vzdialenosť"],["district","okres/štvrť"],["diversity","rozmanitosť"],["document","dokument"],["dose","dávka"],
["drama","dráma"],["drug","liek/droga"],["duty","povinnosť"],["economy","ekonomika"],["edge","okraj/hrana"],
["effect","účinok"],["effort","úsilie"],["election","voľby"],["element","prvok"],["emergency","núdzová situácia"],
["emotion","emócia"],["employer","zamestnávateľ"],["engine","motor"],["entrance","vstup"],["environment","prostredie"],
["episode","epizóda"],["equipment","vybavenie"],["era","éra"],["error","omyl"],["essay","esej"],
["estimate","odhad"],["evidence","dôkaz"],["example","príklad"],["exception","výnimka"],["exercise","cvičenie"],
["exit","východ"],["expense","výdavok"],["expert","expert"],["explanation","vysvetlenie"],["exposure","vystavenie (vplyvu)"],
["extent","rozsah"],["factor","faktor"],["failure","zlyhanie"],["faith","viera"],["fame","sláva"],
["fashion","móda"],["fate","osud"],["feature","vlastnosť/prvok"],["fee","poplatok"],["figure","číslica/postava"],
["file","súbor"],["flame","plameň"],["flavor","chuť/príchuť"],["flight","let"],["flood","povodeň"],
["focus","zameranie"],["fortune","šťastie/majetok"],["foundation","základ/nadácia"],["fraction","zlomok"],["fragment","fragment"],
["frame","rám"],["fuel","palivo"],["function","funkcia"],["fund","fond"],["furniture","nábytok"],
["gap","medzera"],["gender","pohlavie"],["generation","generácia"],["genre","žáner"],["goal","cieľ"],
["grain","zrno"],["growth","rast"],["habit","návyk"],["harm","ujma"],["hazard","riziko"],
["height","výška"],["horizon","horizont"],["household","domácnosť"],["identity","identita"],["image","obraz"],
["impact","dopad"],["income","príjem"],["index","index"],["industry","priemysel"],["injury","zranenie"],
["insight","poznatok/vhľad"],["instance","príklad/prípad"],["instinct","inštinkt"],["institution","inštitúcia"],["instruction","inštrukcia"],
["instrument","nástroj"],["intention","zámer"],["interest","záujem"],["interval","interval"],["introduction","úvod"],
["invention","vynález"],["investment","investícia"],["issue","problém/vydanie"],["item","položka"],["joy","radosť"],
["judgment","úsudok"],["justice","spravodlivosť"],["knowledge","znalosť"],["label","štítok"],["labor","práca (fyzická)"],
["landscape","krajina (výhľad)"],["layer","vrstva"],["length","dĺžka"],["license","licencia"],["list","zoznam"],
["loan","pôžička"],["location","poloha"],["luck","šťastie"],["luxury","luxus"],["machine","stroj"],
["majority","väčšina"],["manner","spôsob (chovania)"],["material","materiál"],["maximum","maximum"],["mechanism","mechanizmus"],
["media","médiá"],["member","člen"],["mess","neporiadok"],["message","správa"],["method","metóda"],
["minimum","minimum"],["minority","menšina"],["mission","misia"],["mixture","zmes"],["mode","režim"],
["model","model"],["mood","nálada"],["motion","pohyb"],["motive","motív"],["movement","hnutie/pohyb"],
["mystery","záhada"],["nation","národ"],["nature","príroda/povaha"],["network","sieť"],["notion","predstava"],
["object","predmet"],["obligation","záväzok"],["occasion","príležitosť"],["opportunity","priaznivá chvíľa"],["option","možnosť"],
["organization","organizácia"],["origin","pôvod"],["outcome","výsledok"],["output","výstup"],["owner","majiteľ"],
["pace","tempo"],["pair","pár"],["panic","panika"],["participant","účastník"],["partner","partner"],
["passage","priechod/úryvok"],["passion","vášeň"],["path","cesta/chodník"],["pattern","vzor"],["peak","vrchol"],
["percentage","percento"],["performance","výkon"],["period","obdobie"],["permission","povolenie"],["phase","fáza"],
["phenomenon","jav"],["philosophy","filozofia"],["photo","fotka"],["piece","kus"],["plot","zápletka"],
["policy","politika (opatrenie)"],["population","populácia"],["portion","porcia/časť"],["position","pozícia"],["possibility","pravdepodobnosť"],
["poverty","chudoba"],["preference","preferencia"],["presence","prítomnosť"],["pressure","tlak"],["priority","priorita"],
["procedure","postup"],["process","proces"],["profession","povolanie"],["profit","zisk"],["proof","potvrdenie"],
["property","majetok/vlastnosť"],["proportion","podiel"],["proposal","návrh"],["protection","ochrana"],["purpose","účel"],
["quality","kvalita"],["quantity","kvantita"],["range","rozpätie"],["rank","hodnosť/poradie"],["rate","miera/sadzba"],
["reaction","reakcia"],["reality","realita"],["recipe","recept"],["region","región"],["relation","vzťah"],
["relationship","partnerský vzťah"],["relief","úľava"],["religion","náboženstvo"],["reputation","povesť"],["resource","zdroj"],
["response","odpoveď/reakcia"],["responsibility","zodpovednosť"],["role","rola"],["root","koreň"],["route","trasa"],
["routine","rutina"],["rule","pravidlo"],["safety","bezpečnosť"],["sample","vzorka"],["scale","mierka/váha"],
["scene","scéna"],["science","veda"],["scope","záber (rozsah pôsobnosti)"],["score","skóre"],["sector","sektor"],
["security","zabezpečenie"],["sense","zmysel"],["sentence","veta"],["series","séria"],["session","stretnutie/sedenie"],
["setting","nastavenie/prostredie"],["shape","tvar"],["shift","zmena/smena"],["side","strana"],["sight","zrak/pohľad"],
["significance","význam"],["site","miesto/stránka"],["situation","situácia"],["size","veľkosť"],["software","softvér"],
["source","prameň"],["space","priestor"],["species","druh"],["speech","reč"],["speed","rýchlosť"],
["spirit","duch"],["stage","fáza/pódium"],["standard","štandard"],["status","status"],["step","krok"],
["stock","zásoba"],["strategy","stratégia"],["strength","sila"],["stress","stres"],["structure","štruktúra"],
["style","štýl"],["substance","látka"],["success","úspech"],["summary","zhrnutie"],["supply","zásoba/ponuka"],
["surface","povrch"],["survey","prieskum"],["symbol","symbol"],["symptom","príznak"],["system","systém"],
["target","terč"],["technique","technika"],["technology","technológia"],["temperature","teplota"],["tendency","tendencia"],
["tension","napätie"],["term","pojem/termín"],["territory","územie"],["text","text"],["theme","téma"],
["theory","teória"],["title","titul/nadpis"],["tone","tón"],["tool","náradie"],["topic","predmet (diskusie)"],
["total","súčet"],["tradition","tradícia"],["trend","trend"],["trial","skúška/proces (súdny)"],["unit","jednotka"],
["variety","pestrosť"],["vehicle","vozidlo"],["version","verzia"],["view","pohľad/výhľad"],["vision","videnie/vízia"],
["volume","objem"],["wage","mzda"],["warning","varovanie"],["wealth","bohatstvo"],["weight","váha"],
["welfare","blaho"],["width","šírka"],["wisdom","múdrosť"],["monday","pondelok"],["tuesday","utorok"],
["wednesday","streda"],["thursday","štvrtok"],["friday","piatok"],["saturday","sobota"],["sunday","nedeľa"],
["january","január"],["february","február"],["april","apríl"],["may","máj"],["june","jún"],
["july","júl"],["august","august"],["september","september"],["october","október"],["november","november"],
["december","december"],["eleven","jedenásť"],["twelve","dvanásť"],["thirteen","trinásť"],["twenty","dvadsať"],
["thirty","tridsať"],["forty","štyridsať"],["fifty","päťdesiat"],["million","milión"],["billion","miliarda"],
["zero","nula"],["second-place","druhé miesto"],["third","tretí"],["fourth","štvrtý"],["fifth","piaty"],
["continent","kontinent"],["ocean","oceán"],["valley","údolie"],["hill","kopec"],["cave","jaskyňa"],
["cliff","útes"],["coast","pobrežie"],["harbor","prístav"],["volcano","sopka"],["earthquake","zemetrasenie"],
["planet","planéta"],["universe","vesmír"],["galaxy","galaxia"],["comet","kométa"],["gravity","gravitácia"],
["oxygen","kyslík"],["hydrogen","vodík"],["chemical","chemikália"],["atom","atóm"],["cell","bunka (biológia)"],
["gene","gén"],["evolution","evolúcia"],["ecosystem","ekosystém"],["pollution","znečistenie"],["recycling","recyklácia"],
["drought","sucho"],["thunder","hrom"],["lightning","blesk"],["fog","hmla"],["frost","mráz"],
["dew","rosa"],["shadow","tieň"],["reflection","odraz"],["engineer","inžinier"],["lawyer","právnik"],
["scientist","vedec"],["artist","umelec"],["actor","herec"],["actress","herečka"],["musician","hudobník"],
["writer","spisovateľ"],["journalist","novinár"],["farmer","farmár"],["chef","šéfkuchár"],["waiter","čašník"],
["waitress","čašníčka"],["cashier","pokladník"],["plumber","inštalatér"],["electrician","elektrikár"],["mechanic","mechanik"],
["carpenter","tesár"],["architect","architekt"],["accountant","účtovník"],["dentist","zubár"],["surgeon","chirurg"],
["pharmacist","lekárnik"],["veterinarian","veterinár"],["pilot","pilot"],["soldier","vojak"],["police officer","policajt"],
["firefighter","hasič"],["politician","politik"],["president","prezident"],["librarian","knihovník"],["photographer","fotograf"],
["designer","dizajnér"],["programmer","programátor"],["translator","prekladateľ"],["hairdresser","kaderník"],["butcher","mäsiar"],
["baker","pekár"],["keyboard","klávesnica"],["mouse (computer)","počítačová myš"],["monitor","monitor"],["password","heslo"],
["username","používateľské meno"],["website","webová stránka"],["browser","prehliadač"],["application","aplikácia"],["charger","nabíjačka"],
["wireless","bezdrôtový"],["bluetooth","bluetooth"],["camera","fotoaparát"],["video","video"],["folder","priečinok"],
["printer","tlačiareň"],["server","server"],["update","aktualizácia"],["backup","záloha"],["virus (computer)","počítačový vírus"],
["cloud (storage)","cloudové úložisko"],["code (programming)","programátorský kód"],["football","futbal"],["basketball","basketbal"],["tennis","tenis"],
["volleyball","volejbal"],["swimming","plávanie"],["running","behanie"],["cycling","cyklistika"],["skiing","lyžovanie"],
["skating","korčuľovanie"],["boxing","box"],["wrestling","zápasenie"],["gym","posilňovňa"],["coach","tréner"],
["referee","rozhodca"],["championship","majstrovstvá"],["medal","medaila"],["trophy","trofej"],["goal (sport)","gól"],
["stadium","štadión"],["gymnastics","gymnastika"],["athlete","atlét"],["opponent","súper"],["victory","víťazstvo"],
["defeat","porážka"],["record (sport)","rekord"],["table","stôl"],["chair","stolička"],["sofa","gauč"],
["bed","posteľ"],["shelf","polica"],["mirror","zrkadlo"],["carpet","koberec"],["curtain","záves"],
["lamp","lampa"],["candle","sviečka"],["blanket","deka"],["pillow","vankúš"],["towel","uterák"],
["broom","metla"],["bucket","vedro"],["vacuum cleaner","vysávač"],["fridge","chladnička"],["oven","rúra"],
["stove","sporák"],["microwave","mikrovlnka"],["dishwasher","umývačka riadu"],["washing machine","práčka"],["sink","umývadlo"],
["toilet","záchod"],["shower","sprcha"],["key","kľúč"],["lock (door)","zámka"],["shelf (bookcase)","knižnica (nábytok)"],
["drawer","zásuvka"],["basket","košík"],["hammer","kladivo"],["nail","klinec"],["screw","skrutka"],
["screwdriver","skrutkovač"],["saw","píla"],["ladder","rebrík"],["rope","lano"],["wire","drôt"],
["glue","lepidlo"],["tape","páska"],["scissors","nožnice"],["needle","ihla"],["thread","niť"],
["knife","nôž"],["fork","vidlička"],["spoon","lyžica"],["plate","tanier"],["bowl","miska"],
["cup","šálka"],["glass (drinking)","pohár"],["napkin","obrúsok"],["tray","podnos"],["pan","panvica"],
["pot","hrniec"],["lid","pokrievka"],["although","hoci"],["however","avšak"],["therefore","preto"],
["meanwhile","medzitým"],["unless","pokiaľ nie"],["because","pretože"],["despite","napriek"],["instead","namiesto toho"],
["besides","okrem toho"],["otherwise","inak"],["nowadays","v dnešnej dobe"],["eventually","nakoniec"],["gradually","postupne"],
["suddenly","zrazu"],["nearly","približne"],["almost","takmer"],["barely","sotva"],["fairly","celkom (dosť)"],
["extremely","extrémne"],["completely","úplne"],["entirely","celkom (úplne)"],["properly","poriadne"],["directly","priamo"],
["exactly","presne"],["obviously","očividne"],["actually","vlastne"],["basically","v podstate"],["generally","všeobecne"],
["particularly","zvlášť"],["especially","obzvlášť"],["clearly","jasne"],["simply","jednoducho"],["merely","iba"],
["rather","radšej"],["quite","dosť"],["forward","dopredu"],["backward","dozadu"],["upward","nahor"],
["downward","nadol"],["sideways","bokom"],["indoors","vnútri"],["outdoors","vonku"],["upstairs","hore (na poschodí)"],
["downstairs","dole (na prízemí)"],["abroad","v zahraničí"],["ambulance","sanitka"],["accident","nehoda"],["injury (medical)","poranenie"],
["surgery","operácia"],["treatment","liečba"],["vaccine","vakcína"],["virus","vírus"],["bacteria","baktéria"],
["infection","infekcia"],["appointment (doctor)","termín u lekára"],["prescription","recept (na lieky)"],["pharmacy","lekáreň"],["clinic","klinika"],
["ward","oddelenie (nemocnica)"],["passport","pas"],["visa","vízum"],["customs","colnica"],["embassy","veľvyslanectvo"],
["citizen (nation)","občan (štátu)"],["currency","mena"],["exchange rate","výmenný kurz"],["invoice","faktúra"],["contract (legal)","zmluva (právna)"],
["signature","podpis"],["insurance","poistenie"],["pension","dôchodok"],["tax","daň"],["loan (bank)","úver"],
["mortgage","hypotéka"],["stock market","burza"],["shareholder","akcionár"],["profit margin","zisková marža"],["headquarters","ústredie"],
["branch (company)","pobočka"],["client","klient"],["supplier","dodávateľ"],["warehouse","sklad"],["inventory","zásoby (skladu)"],
["shipment","zásielka"],["negotiation","vyjednávanie"],["agreement","zmluvná dohoda"],["merger","fúzia"],["startup","startup"],
["entrepreneur","podnikateľ"],["guitar","gitara"],["piano","klavír"],["violin","husle"],["drum","bubon"],
["flute","flauta"],["trumpet","trúbka"],["orchestra","orchester"],["concert","koncert"],["melody","melódia"],
["rhythm","rytmus"],["lyrics","text piesne"],["album","album"],["singer","spevák"],["band","kapela"],
["audience (concert)","divák (koncertu)"],["painting","maľba"],["sculpture","socha"],["drawing","kresba"],["canvas","plátno (na maľovanie)"],
["brush","štetec"],["exhibition","výstava"],["gallery","galéria"],["theater","divadlo"],["stage (theater)","javisko"],
["script","scenár"],["elephant","slon"],["giraffe","žirafa"],["tiger","tiger"],["zebra","zebra"],
["monkey","opica"],["kangaroo","klokan"],["wolf","vlk"],["fox","líška"],["deer","jeleň"],
["squirrel","veverička"],["hedgehog","jež"],["frog","žaba"],["turtle","korytnačka"],["lizard","jašterica"],
["crocodile","krokodíl"],["shark","žralok"],["whale","veľryba"],["dolphin","delfín"],["octopus","chobotnica"],
["crab","krab"],["shrimp","kreveta"],["ant","mravec"],["fly (insect)","mucha"],["mosquito","komár"],
["wasp","osa"],["beetle","chrobák"],["worm","červ"],["snail","slimák"],["chicken (animal)","kura"],
["duck","kačica"],["goose","hus"],["turkey (animal)","morka"],["goat","koza"],["donkey","osol"],
["camel","ťava"],["garlic","cesnak"],["pepper (spice)","korenie"],["cinnamon","škorica"],["vanilla","vanilka"],
["honey","med"],["jam","džem"],["ketchup","kečup"],["mustard","horčica"],["mayonnaise","majonéza"],
["vinegar","ocot"],["flour","múka"],["yeast","droždie"],["dough","cesto"],["pastry","pečivo"],
["biscuit","sušienka"],["pancake","palacinka"],["sandwich","sendvič"],["pizza","pizza"],["burger","hamburger"],
["fries","hranolky"],["noodles","rezance"],["dumpling","knedľa"],["sausage","párok"],["ham","šunka"],
["bacon","slanina"],["lettuce","šalát (list.zelenina)"],["cucumber","uhorka"],["carrot","mrkva"],["pepper (vegetable)","paprika"],
["mushroom","huba"],["cabbage","kapusta"],["spinach","špenát"],["pumpkin","tekvica"],["corn","kukurica"],
["peas","hrášok"],["lemon","citrón"],["strawberry","jahoda"],["grape","hrozno"],["watermelon","dyňa"],
["pineapple","ananás"],["cherry","čerešňa"],["peach","broskyňa"],["pear","hruška"],["plum","slivka"],
["raspberry","malina"],["nut","orech"],["almond","mandľa"],["peanut","arašid"],["seed","semienko"],
["spice","koreniny"],["motorcycle","motorka"],["truck","nákladné auto"],["van","dodávka"],["subway","metro"],
["tram","električka"],["helicopter","helikoptéra"],["rocket","raketa"],["engine (vehicle)","motor (vozidla)"],["fuel tank","palivová nádrž"],
["wheel","koleso"],["brake","brzda"],["steering wheel","volant"],["seatbelt","bezpečnostný pás"],["garage","garáž"],
["parking lot","parkovisko"],["skyscraper","mrakodrap"],["tower","veža"],["castle","hrad"],["palace","palác"],
["monument","pamätník"],["statue","socha (pomník)"],["fountain","fontána"],["cemetery","cintorín"],["prison","väzenie"],
["courtroom","súdna sieň"],["warehouse (storage)","skladová hala"],["barn","stodola"],["greenhouse","skleník"],["cottage","chalupa"],
["kindergarten","materská škola"],["classroom","trieda (miestnosť)"],["principal","riaditeľ školy"],["professor","profesor"],["lecture","prednáška"],
["textbook","učebnica"],["notebook","zošit"],["dictionary","slovník"],["novel","román"],["poem","báseň"],
["magazine","časopis"],["newspaper","noviny"],["headline","titulok"],["publisher","vydavateľ"],["author (writer)","autor knihy"],
["chapter (book)","kapitola knihy"],["plot (story)","dej (príbehu)"],["character (fiction)","postava (v príbehu)"],["setting (story)","prostredie deja"],["ending","koniec (príbehu)"],
["trust (relationship)","dôvera (vo vzťahu)"],["betrayal","zrada"],["forgiveness","odpustenie"],["jealousy","žiarlivosť"],["affection","náklonnosť"],
["romance","romantika"],["engagement","zásnuby"],["divorce","rozvod"],["breakup","rozchod"],["reunion","stretnutie po čase"],
["compassion","súcit"],["sympathy","sústrasť"],["gratitude","vďačnosť"],["disappointment","sklamanie"],["frustration","frustrácia"],
["excitement","vzrušenie/nadšenie"],["relief (emotion)","úľava (pocit)"],["boredom","nuda"],["curiosity","zvedavosť"],["confusion","zmätok"],
["assume","domnievať sa"],["assist","asistovať"],["adapt","prispôsobiť sa"],["adjust","upraviť"],["admit","priznať"],
["approve","schváliť"],["arrange","usporiadať"],["assemble","zostaviť"],["attach","pripojiť"],["attract","priťahovať"],
["blame","obviňovať"],["bother","obťažovať"],["breathe","dýchať"],["broadcast","vysielať"],["capture","zachytiť"],
["clarify","objasniť"],["combine","kombinovať"],["command","veliť"],["compete","súťažiť"],["compose","skomponovať"],
["conclude","uzavrieť (záver)"],["conduct","viesť (výskum)"],["conquer","dobyť"],["construct","skonštruovať"],["consult","konzultovať"],
["consume","konzumovať"],["convince","utvrdiť v presvedčení"],["cooperate","spolupracovať"],["coordinate","koordinovať"],["correspond","korešpondovať"],
["counter","namietať"],["crash","havarovať"],["criticize","kritizovať"],["cultivate","pestovať"],["curl","kučeraviť"],
["dedicate","venovať sa"],["defend","brániť"],["define","definovať"],["delay (verb)","zdržať"],["demonstrate","demonštrovať"],
["depend","závisieť"],["depict","zobrazovať"],["derive","odvodiť"],["detect","zistiť/odhaliť"],["determine","určiť"],
["devote","zasvätiť"],["differ","líšiť sa"],["diminish","znižovať sa"],["disappoint","sklamať"],["dismiss","prepustiť/odmietnuť"],
["dispose","zbaviť sa"],["dominate","dominovať"],["donate","darovať"],["drift","unášať sa"],["drown","utopiť sa"],
["dwell","prebývať"],["elect","zvoliť (voľbami)"],["eliminate","eliminovať"],["embrace","objať/prijať"],["emerge","vynoriť sa"],
["emphasize","zdôrazniť"],["enable","umožniť"],["endure","vydržať"],["enforce","presadzovať"],["engage","zapojiť"],
["enhance","vylepšiť"],["ensure","zabezpečiť"],["equip","vybaviť"],["establish","založiť"],["estimate (verb)","odhadnúť"],
["evaluate","vyhodnotiť"],["evolve","vyvíjať sa"],["exceed","prekročiť"],["exclude","vylúčiť"],["execute","vykonať"],
["exhibit","vystavovať"],["extend","predĺžiť"],["extract","extrahovať"],["facilitate","uľahčiť"],["fascinate","fascinovať"],
["fasten","upevniť"],["flee","utiecť (pred nebezpečenstvom)"],["flourish","prekvitať"],["focus (verb)","sústrediť sa"],["forbid","zakázať"],
["foster","podporovať (rozvoj)"],["fulfil","splniť"],["gather","zhromaždiť"],["generate","generovať"],["glance","pozrieť sa letmo"],
["grab","schmatnúť"],["grip","zovrieť"],["harvest","zberať úrodu"],["haunt","strašiť (o duchu)"],["heat","zohriať"],
["highlight","zvýrazniť"],["hint","naznačiť"],["illustrate","ilustrovať"],["implement","implementovať"],["imply","naznačovať"],
["impose","uložiť (povinnosť)"],["impress","urobiť dojem"],["incorporate","začleniť"],["indicate","naznačovať/indikovať"],["induce","vyvolať"],
["infect","nakaziť"],["inherit","zdediť"],["initiate","iniciovať"],["insert","vložiť"],["inspire","inšpirovať"],
["integrate","integrovať"],["interact","interagovať"],["interfere","zasahovať"],["interrupt","prerušiť"],["intervene","zasiahnuť"],
["invade","napadnúť (vojensky)"],["invest","investovať"],["isolate","izolovať"],["justify","ospravedlniť (zdôvodniť)"],["lack","chýbať/postrádať"],
["last (verb)","trvať"],["locate","nájsť polohu"],["maintain","udržiavať"],["manipulate","manipulovať"],["manufacture","vyrábať (priemyselne)"],
["migrate","migrovať"],["minimize","minimalizovať"],["modify","upraviť/modifikovať"],["mount","namontovať"],["neglect","zanedbávať"],
["negotiate","vyjednávať"],["nominate","nominovať"],["oblige","zaväzovať"],["occupy","obsadiť"],["oppose","postaviť sa proti"],
["outline","načrtnúť"],["overcome","prekonať"],["overlook","prehliadnuť (nevšimnúť si)"],["overtake","predbehnúť"],["overwhelm","zavaliť/premôcť"],
["owe","dlžiť"],["perceive","vnímať"],["permit (verb)","dovoliť (formálne)"],["pinpoint","presne určiť"],["portray","zobraziť/vykresliť"],
["postpone","odložiť"],["preserve","zachovať"],["proceed","pokračovať (ísť ďalej)"],["process (verb)","spracovať"],["prohibit","zakázať (oficiálne)"],
["propose","navrhnúť (formálne)"],["pursue","usilovať sa o"],["reassure","upokojiť"],["rebuild","znovu postaviť"],["recall (memory)","spomenúť si na"],
["reckon","odhadovať/domnievať sa"],["reconsider","znovu zvážiť"],["reduce (verb)","redukovať"],["reflect (think)","zamyslieť sa"],["refresh","obnoviť/osviežiť"],
["regard","považovať za"],["reinforce","posilniť (konštrukciu)"],["reject","zavrhnúť"],["relate","súvisieť"],["relieve","uľaviť"],
["rely (on)","spoľahnúť sa na"],["renew","obnoviť (platnosť)"],["renovate","zrenovovať"],["resemble","podobať sa"],["reserve","rezervovať"],
["resign","rezignovať"],["resolve","vyriešiť (problém)"],["restore","obnoviť (pôvodný stav)"],["restrict","obmedziť (regulovať)"],["retain","udržať si"],
["retire","odísť do dôchodku"],["retrieve","znovu získať"],["reverse","zvrátiť"],["revise","prepracovať"],["reward (verb)","odmeniť (koho)"],
["rotate","otáčať sa"],["scatter","rozptýliť"],["seize","zmocniť sa"],["shift (verb)","presunúť"],["shrink","zmenšiť sa"],
["simplify","zjednodušiť"],["specify","upresniť"],["stabilize","stabilizovať"],["starve","hladovať"],["strive","usilovať sa"],
["subscribe","predplatiť si"],["substitute","nahradiť (niečím iným)"],["summarize","zhrnúť"],["supervise","dohliadať"],["supplement","doplniť"],
["surrender","vzdať sa"],["sustain","udržiavať (dlhodobo)"],["tackle","riešiť (problém)"],["target (verb)","zamerať sa na"],["terminate","ukončiť (zmluvu)"],
["tolerate","tolerovať"],["trace","vystopovať"],["transform","premeniť"],["transmit","prenášať (signál)"],["undergo","podstúpiť"],
["undertake","podujať sa"],["unify","zjednotiť (spojiť)"],["utilize","využiť"],["verify","overiť"],["violate","porušiť"],
["withdraw","stiahnuť sa/vybrať (peniaze)"],["yield","vzdať sa/priniesť (výsledok)"],
];
